### ISSUE TITLE
No 'Ethernet' Internet Sharing option on MBP 2015. 

### ISSUE THREAD

**Issue by miloszfalinski** [taintedzodiac/relaymyhome#23]
Since there's no ethernet port on new MacBooks, there's no Ethernet sharing option:  
<img width="436" alt="screen shot 2015-09-21 at 10 16 40" src="https://cloud.githubusercontent.com/assets/303462/9987632/de10b5ac-6049-11e5-8cd7-098d461e624f.png">

Is there any known workaround for this?

**Comment by PedroBernils** [comment]
You need to get the internet from elsewhere, the best bet seems to be make a hotspot with your phone and connect via bluetooth.

**Comment by oboroc** [comment]
You can buy Apple "Thunderbolt to Gigabit Ethernet Adapter" and then it's like on macs with built-in network port
