### ISSUE TITLE
MACs not cycing (El Capitan 10.11.1)

### ISSUE THREAD

**Issue by efroriz** [taintedzodiac/relaymyhome#25]
Hi.

I've been back to RelayMyHome today after several months. Always worked perfectly on Yosemite. I've downloaded the latest update to use it on El Capitan.

I launch the script as usual, only it doesn't actually cycle between addresses. This is the line I get:

Spoofing en0 to 4E:53:50:4F:4F:00 for 90 seconds

over and over again. It never changes MAC. Tried with quick and full mode. The first time I launched it I got my Streetpasses all right, so the script is working as intended... except it always relays me to the same MAC address.

Any solution to this? Thanks.

**Comment by StormNights** [comment]
Im in the same boat as you Spoofing en1 to 4E:53:50:4F:4F:00 over and over again... Hope there is a fix here soon..

**Comment by stepquick** [comment]
@taintedzodiac have you seen this? It appears that the script only returns one from that list of mac addresses, and it's not random.

**Comment by egamboau** [comment]
I had the same issue, and fixed on my local copy. I will create a pull request for that this weekend.

**Comment by markcerqueira** [comment]
Can confirm the gist @stepquick shared fixes the script for me on El Capitan 10.11.4.

**Comment by tapjoy-itservices** [comment]
@markcerqueira @taintedzodiac also confirming @stepquick share fixes the issue in El Captain 10.11.4, and that this issue is still open.

**Comment by taintedzodiac** [comment]
Thanks for the confirmations, all. Merged and closed!
