### ISSUE TITLE
No Streetpass hits

### ISSUE THREAD

**Issue by hvittsalt** [taintedzodiac/relaymyhome#29]
I am no longer able to get Streetpass-hits ever since the 11.1-update. 
Is there something that can be done about that?

**Comment by ryanhilton** [comment]
Yeah, same for me

**Comment by hvittsalt** [comment]
I really hope this can be fixed somehow - since I live in the middle of nowhere I haven't gotten a single Streetpass hit for over two weeks

**Comment by HalF75** [comment]
Yeah I have the same problem. Any news on this?

**Comment by HalF75** [comment]
@taintedzodiac, any news on this? Best regards!

**Comment by ryanhilton** [comment]
NZ@McD1 doesn't work anymore, change the shared network name to attwifi
That worked for me!

**Comment by taintedzodiac** [comment]
@HalF75 Haven't had a chance to take a look yet, planning to in the coming days.

@ryanhilton I'm going to try that first, thanks for the heads up!

**Comment by HalF75** [comment]
Thanks for your reply. When I get home I'll try with the old network name.
I really need this to work! :|

**Comment by hvittsalt** [comment]
I tried changing the name to attwifi and it seems to be working again :)

**Comment by ryanhilton** [comment]
@taintedzodiac @hvittsalt @HalF75 yeah, I found out about the change here: [http://homepass.info](http://homepass.info)

**Comment by HalF75** [comment]
Yes, that works for me too. Thanks for the help!

**Comment by Bacilligon** [comment]
Hello, I'm sorry to be a bother! I have followed the instructions on the ReadMe and made sure to set the SSID of the network my laptop is sharing to "attwifi". The script seems to be cycling through MAC addresses just fine, but even so I am not receiving any Streetpasses. My 3DS is on and connected to the "attwifi" that's being shared by my laptop. Could there be something else I'm missing? Thank you for your time!

**Comment by HalF75** [comment]
I don't have the "attwifi" network on my 3DS, try removing it from the DS.
Also check that you don't have a firewall on your mac, my doesn't work if
my firewall software is up and running.

This are my solutions, let me know if this fixed it.

Best regards,
Ricardo Carvalho

**Comment by Bacilligon** [comment]
HalF75, you were right and I feel very silly! Disconnecting my 3DS from the "attwifi" network seems to have been the solution all along, as within 30 seconds of running the script that wonderful green light lit up! Thank you for the suggestion! :)
