### ISSUE TITLE
Is it nor working again

### ISSUE THREAD

**Issue by HalF75** [taintedzodiac/relaymyhome#32]
Hi.

I'm not getting any hits, did it stop working again? 
Can anyone confirm?

Best regards,
Ricardo Carvalho

**Comment by taintedzodiac** [comment]
I haven't used it in quite some time but if someone does figure out the issue before I get to it, please do open a PR.

**Comment by HalF75** [comment]
Hi.

It's working I just messed up the setup.

Best regards,
Ricardo Carvalho


‌
