### ISSUE TITLE
I don't know if this is okay

### ISSUE THREAD

**Issue by AnestisTzogias** [taintedzodiac/relaymyhome#33]
Ok so i tried this and when i type the command ./relaymyhomefull, the terminal replies: ''-bash: ./relaymyhome: is a directory''. Is there a problem with that or i can proceed normally? Thanks in advance!

**Comment by taintedzodiac** [comment]
Sounds like you're trying to run it in the parent directory. Try `cd relaymyhome` and then see if that puts you into the correct directory.
