### ISSUE TITLE
Streetpass collection

### ISSUE THREAD

**Issue by HalF75** [taintedzodiac/relaymyhome#34]
Hi.

This is not a bug, just an idea. Is there any way to send my streetpass to the relaymyhome and have people collecting that streetpass at another location? 
For example, can I add my mac-address to an API and then everytime I use the relaymyhome I'll just cycle throw all (or maybe just a few) of the mac address and collect streetpasses from those mac addresses? 

Does it make sense? Does anyone know if it's possible?

**Comment by taintedzodiac** [comment]
Closing this since Streetpass Relay is no longer a thing, so the script itself is no longer useful. Thanks though!
